#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PIApp.Droid.Resource", IsApplication=true)]

namespace PIApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drinking = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int profile = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int stats = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int status = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int cmdCancel = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int cmdDrink = 2131099655;
			
			// aapt resource value: 0x7f060020
			public const int cmdSave = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int dpBirthday = 2131099679;
			
			// aapt resource value: 0x7f06000a
			public const int elozoKor = 2131099658;
			
			// aapt resource value: 0x7f06001b
			public const int genderGroup = 2131099675;
			
			// aapt resource value: 0x7f060004
			public const int lvBrandType = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int lvDrinkType = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int lvQuantity = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public const int partyEnd = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int partyName = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int partylayout = 2131099657;
			
			// aapt resource value: 0x7f06001d
			public const int rbFemale = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int rbMale = 2131099676;
			
			// aapt resource value: 0x7f06000c
			public const int startParty = 2131099660;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f06001e
			public const int textView10 = 2131099678;
			
			// aapt resource value: 0x7f060003
			public const int textView2 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int textView3 = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int textView4 = 2131099648;
			
			// aapt resource value: 0x7f060012
			public const int textView5 = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int textView6 = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int textView7 = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int textView8 = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int textView9 = 2131099674;
			
			// aapt resource value: 0x7f060017
			public const int txtAddress = 2131099671;
			
			// aapt resource value: 0x7f06000f
			public const int txtFirstname = 2131099663;
			
			// aapt resource value: 0x7f060013
			public const int txtHeight = 2131099667;
			
			// aapt resource value: 0x7f060019
			public const int txtIce = 2131099673;
			
			// aapt resource value: 0x7f060010
			public const int txtLastname = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int txtPassword = 2131099665;
			
			// aapt resource value: 0x7f060015
			public const int txtWeight = 2131099669;
			
			// aapt resource value: 0x7f06000b
			public const int ujKor = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DrinkPickerLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PartyLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int settingsLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int StatisticsLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int StatusLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TravelLayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int abszint = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int bor = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int brandy = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ciderradler = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int gin = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int keseru = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int koktellikor = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int konyak = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int likor = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int longdrink = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int palinka = 2130968586;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int title_activity_main = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
