#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PIApp.Droid.Resource", IsApplication=true)]

namespace PIApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drinking = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int profile = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int stats = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int status = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int cmdDrink = 2131034118;
			
			// aapt resource value: 0x7f05001f
			public const int cmdSave = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int dpBirthday = 2131034142;
			
			// aapt resource value: 0x7f050008
			public const int elozoKor = 2131034120;
			
			// aapt resource value: 0x7f05001a
			public const int genderGroup = 2131034138;
			
			// aapt resource value: 0x7f050003
			public const int lvBrandType = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int lvDrinkType = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int lvQuantity = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int partyEnd = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int partyName = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int partylayout = 2131034119;
			
			// aapt resource value: 0x7f05001c
			public const int rbFemale = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int rbMale = 2131034139;
			
			// aapt resource value: 0x7f05000a
			public const int startParty = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f05001d
			public const int textView10 = 2131034141;
			
			// aapt resource value: 0x7f050002
			public const int textView2 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int textView3 = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int textView4 = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int textView5 = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int textView6 = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int textView7 = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int textView8 = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int textView9 = 2131034137;
			
			// aapt resource value: 0x7f050016
			public const int txtAddress = 2131034134;
			
			// aapt resource value: 0x7f05000d
			public const int txtFirstname = 2131034125;
			
			// aapt resource value: 0x7f050012
			public const int txtHeight = 2131034130;
			
			// aapt resource value: 0x7f050018
			public const int txtIce = 2131034136;
			
			// aapt resource value: 0x7f05000e
			public const int txtLastname = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int txtPassword = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int txtWeight = 2131034132;
			
			// aapt resource value: 0x7f050009
			public const int ujKor = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DrinkPickerLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PartyLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int settingsLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int StatisticsLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int StatusLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TravelLayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int title_activity_main = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
